### ISSUE TITLE
Investigación del algoritmo Centroide más cercano

### ISSUE THREAD

**Issue by LuciaCairo** [agussanchez97/ia-uncuyo-2021#16]
Definición, función, ventajas, desventajas, ejemplos.

**Comment by agussanchez97** [comment]
Investigue como funciona el algoritmo, resumidamente es un algoritmo de clasificación,  se basa en encontrar el centroide más cercano a un punto de prueba para asignarle una clase.
El funcionamiento se puedo explicar en 3 simples pasos:
1) Encontrar el centroide para cada con el conjunto de entrenamiento
2) Luego, para cualquier punto 'X',se calculan las distancias entre el punto X y el centroide de cada clase.
3) De todas las distancias calculadas, se selecciona la distancia mínima. El centroide al que la distancia del punto dado es mínima, es el que define la clase del punto X.

En cuanto a la implementación,el algoritmo, no está implementado directamente en R, pero se puede lograr utilizando funciones y operaciones básicas de manipulación de datos.

Ventajas y Desventajas las menciono a continuación y seran explicadas en el informe final.

Ventajas: 
-Fácil implementación
-Eficiente computacionalmente
-Fácil interpretación

Desventajas:
-Sensible a datos atípicos o valores extremos.
-Sensible a distribuciones desbalanceadas.
-Suposición de igual varianza.
-No considera interacciones entre características.

Bibliografia:
https://www.sciencedirect.com/topics/computer-science/nearest-centroid
https://www.geeksforgeeks.org/ml-nearest-centroid-classifier/
https://machinelearningmastery.com/nearest-shrunken-centroids-with-python/#:~:text=Nearest%20Centroids%20Algorithm,-Nearest%20Centroids%20is&text=The%20algorithm%20involves%20first%20summarizing,class)%20in%20the%20training%20set.
