### ISSUE TITLE
Anteproyecto: Falta codigo del proyecto

### ISSUE THREAD

**Issue by harpomaxx** [agussanchez97/ia-uncuyo-2021#2]
FALTA algo como esto:

Para Titulo "Algoritmo genético  problemas de tráfico vehicular”
Un codigo del proyecto: “GATRAF”

Mirar las indicaciones para armar el anteproyecto

**Comment by agussanchez97** [comment]
Realizado , confirmar si el titulo hace la suficiente referencia al trabajo
