### ISSUE TITLE
Tanto para centroides como glmnet crear una subseccion con los resultados finales en test

### ISSUE THREAD

**Issue by harpomaxx** [agussanchez97/ia-uncuyo-2021#59]

**Comment by LuciaCairo** [comment]
se agregaron tablas resumiendo los resultados finales de ambos algoritmos en su respectiva seccion en el "Analisis de resultados"

**Tabla resumen del algoritmo centroide :**

| Modelo    | Precicion     |
|------------|-------------|
| Centroide | 0,70 |
| Centroide con variacion de la distancia | 0,80 |
| Centroide con variacion de numero de centroides | 0,80 |

**Tabla resumen del algoritmo glmnet :**

| Modelo    | Precicion     |
|------------|-------------|
| standardize = FALSE, alpha= defecto, lambda= defecto | 0,89  |
| standardize = TUE, alpha= defecto, lambda= defecto | 0,935 |
| standardize = TRUE, alpha= 0.7, lambda= defecto | 0,938  |
| standardize = TRUE, alpha= 0.7, lambda= 0.01  | 1 |
