### ISSUE TITLE
faltaria una tabla o un simple grafico que resalte las diferencias entre los dos algoritmos.

### ISSUE THREAD

**Issue by harpomaxx** [agussanchez97/ia-uncuyo-2021#61]
Me gustaria durante la discusion de los resultados algun grafico o tabla incluso que muestre los mejores resultados de ambos algoritmos. Idealmente la diferencia que hay en CV y Test, pero con poner los datos de solo test alcanzaria.

**Comment by LuciaCairo** [comment]
se realizo una tabla para comparar ambos algoritmos en el "analisis de discucion"
| Modelo    | Precicion     |
|------------|-------------|
| Centroide mas cercano | 0,70 |
| Centroide mas cercano mejorado | 0,80 |
| Algortimo GLMNET | 0,93 |
| Algortimo GLMNET mejorado | 1,00 |
